#line 2 "lex_sql.cpp"
/*
这里的代码会被复制到lex_sql.cpp的最开始位置
定义yy_size_t的原因是因为flex生成的代码，会使用yy_size_t与其他类型的数字
做比较，导致编译报警
*/
#define YY_TYPEDEF_YY_SIZE_T
typedef int yy_size_t;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在每次运行yylex()最开始的地方 */
#define YY_USER_INIT                                         \
  yycolumn = 0;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在解析一个token之后，也可以在网上找到大量的参考资料 */
/* 我们在这里设置当前解析的token的位置信息，这样在yacc中就可以使用这些信息了 */
#define YY_USER_ACTION                                       \
do {                                                         \
  yylloc->first_line   = yylloc->last_line = yylineno;       \
  yylloc->first_column = yycolumn;                           \
  yylloc->last_column  = yylloc->first_column + yyleng - 1;  \
  yycolumn += yyleng;                                        \
}                                                            \
while (0);

#line 26 "lex_sql.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,   91,   89,    1,    2,   89,   89,
       89,   72,   73,   84,   82,   74,   83,   14,   85,   11,
       13,   79,   75,   81,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   90,   78,    0,   87,    0,
       88,    0,   11,    0,   76,   77,   80,    0,    0,   71,
       71,   71,   67,   71,   71,   65,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   16,
       62,   71,   71,   71,   71,   71,   71,   71,   26,   69,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   71,    0,   12,    4,    0,   34,    0,   66,   57,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   44,   71,   71,   71,   56,   55,   54,   71,   71,
       71,   71,   40,   71,   58,   71,   71,   71,   71,   71,
       71,   71,   71,    0,    0,    0,    0,    0,    0,   71,
       30,   45,   71,   71,   71,   50,   47,   71,   19,   21,
       71,   15,   71,   71,   32,   71,   71,   18,   71,   71,
       71,   71,   36,   61,   53,   48,    0,    0,   63,   71,
       71,   71,   27,    0,   28,   71,   49,   71,   71,   71,

       23,   71,    0,    3,    0,    0,   41,   71,   59,   71,
       71,   71,   71,   46,   68,   71,   25,   71,   60,   71,
        0,    0,   64,   71,   71,    0,   22,   71,   71,   71,
       33,    0,   10,    0,    0,    0,   42,    0,   20,   38,
       17,   71,   70,   51,   35,    0,    0,    0,    0,    0,
        0,   71,   29,    0,    0,    0,   24,   31,   39,   37,
        0,    0,    0,   52,    0,    0,   71,    0,    0,    0,
        7,    0,    0,    0,    6,    5,   43,    8,    0,    0,
       86,    0,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
        1,    1,    1,    1,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    3,    4,    1,    5,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6
    } ;

static const flex_int16_t yy_base[308] =
    {   0,
        0,    0,    0,    0,  437, 1386, 1386, 1386,  414,  426,
       65, 1386, 1386, 1386, 1386, 1386,  414, 1386, 1386,   59,
     1386,   57, 1386,  408,   66,   70,  129,   76,   93,   80,
       97,  133,  139,  116,  103,  146,  158,  175,  181,  195,
      244,  204,  218,  250,  233, 1386, 1386,  414, 1386,  412,
     1386,   71,   88,  402, 1386, 1386, 1386,  399,    0,   85,
      152,  224,  210,  254,  277,  270,  286,  296,  300,  306,
      310,  321,  326,  333,  338,  342,  350,  358,  376,  422,
      367,  388,  393,  400,  409,  415,  426,  438,  380,  444,
      451,  484,  464,  477,  488,  492,  499,  504,  513,  525,

      531,  539,  117,  396,  394,   72,  518,   83,  552,  559,
      563,  571,  575,  582,  587,  591,  603,  609,  613,  595,
      619,  629,  635,  639,  650,  654,  660,  664,  679,  686,
      691,  705,  710,  714,  719,  733,  737,  741,  745,  758,
      762,  766,  771,  776,  785,  791,  797,  802,  809,  814,
      818,  823,  835,  196,  389,  385,  112,  115,    0,  840,
      844,  849,  862,  866,  870,  874,  880,  888,  895,  899,
      905,  909,  913,  917,  924,  928,  933,  937,  942,  949,
      956,  960,  964,  971,  975,  983,    0,    0,  987,  992,
      997, 1002, 1013,    0, 1018, 1022, 1026, 1030, 1036, 1041,

     1045, 1049,  179,  381,  137,  212, 1054, 1064, 1071, 1080,
     1085, 1075, 1093, 1099, 1103, 1107, 1111, 1119, 1125, 1129,
      234,  266, 1133, 1137, 1141,  285, 1148, 1152, 1158, 1162,
     1166,  228, 1386,  371,  369,  287, 1172,    0, 1176, 1180,
     1184, 1192, 1198, 1202, 1206,  357,  356,  312,  335,  318,
      316, 1215, 1219,  295,  297,  320, 1223, 1227, 1231, 1235,
      586,  276,  329, 1240,  272,  261, 1244,  260,  246,  193,
      257,  252,  230,  359,  211,  206, 1249,  186,  375,  182,
     1386,  178,  153, 1386, 1301, 1307, 1313, 1317,  133, 1321,
     1325, 1329,  130,  114,   97,   85, 1334, 1339, 1344, 1349,

     1354,   68, 1359, 1364, 1369, 1374, 1379
    } ;

static const flex_int16_t yy_def[308] =
    {   0,
      284,    1,  285,  285,  284,  284,  284,  284,  284,  286,
      287,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  284,  284,  286,  284,  287,
      284,  287,  284,  284,  284,  284,  284,  284,  289,  290,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  287,  284,  284,  291,  288,  284,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  287,  284,  292,  291,  284,  293,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  294,  295,  288,  288,
      288,  288,  288,  296,  288,  288,  288,  288,  288,  288,

      288,  288,  287,  284,  284,  297,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      298,  299,  288,  288,  288,  300,  288,  288,  288,  288,
      288,  287,  284,  284,  301,  297,  288,  302,  288,  288,
      288,  288,  288,  288,  288,  284,  303,  298,  284,  304,
      299,  288,  288,  284,  305,  300,  288,  288,  288,  288,
      287,  284,  306,  288,  284,  284,  288,  284,  287,  287,
      284,  284,  307,  306,  284,  284,  288,  284,  287,  284,
      284,  287,  284,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_nxt[1458] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   35,   35,   40,   41,   42,
       43,   44,   45,   35,   35,   35,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   35,   35,   40,   41,   42,   43,   44,   45,   35,
       35,   51,   54,  263,   53,   55,   56,   51,   58,   59,
       52,   60,   58,   59,  155,   60,  103,  156,   58,   59,
      226,   60,   58,   59,   65,   60,   71,   58,   59,   62,

       72,   54,  222,   53,   63,   58,   59,   64,   60,   58,
       59,   75,   60,   73,   66,   58,   59,   76,   60,  221,
       65,  158,   71,   51,  155,   62,   72,  156,   58,   59,
       63,   60,  154,   64,   77,  206,   74,   75,  106,   73,
       66,   58,   59,   76,   60,   58,   59,  158,   60,   67,
       82,   58,   59,   78,   60,  205,   68,   79,   58,   59,
       77,   60,   74,   69,   58,   59,   70,   60,  283,  233,
       58,   59,   80,   60,   83,   67,   82,   81,   85,   78,
       84,  205,   68,   79,  281,   51,   86,   58,   59,   69,
       60,  232,   70,   58,   59,  233,   60,  283,   80,   51,

       83,  278,   51,   81,   85,  269,   84,   58,   59,   87,
       60,  203,   86,  108,   89,   88,   58,   59,   90,   60,
      234,  276,   58,   59,   96,   60,  275,  235,   97,   91,
       58,   59,  109,   60,   51,   87,   58,   59,  272,   60,
       89,   88,  246,  261,   90,   58,   59,  107,   60,  247,
       96,   98,   51,   99,   97,   91,   58,   59,  109,   60,
      102,  279,   58,   59,  280,   60,   58,   59,   92,   60,
      100,   93,  271,  107,  249,  278,  276,   98,  101,   99,
      110,  250,   58,   59,   94,   60,  102,  275,   95,   58,
       59,  271,   60,  254,   92,  234,  100,   93,   58,   59,

      255,   60,  235,  111,  101,  254,  110,  268,   58,   59,
       94,   60,   58,   59,   95,   60,  113,  112,   58,   59,
      246,   60,   58,   59,  249,   60,  249,  247,  254,  111,
      116,  250,  114,   58,   59,  255,   60,  272,   58,   59,
      115,   60,  113,  112,  273,   58,   59,  266,   60,  117,
       58,   59,  118,   60,   58,   59,  116,   60,  114,  119,
      120,  121,   58,   59,  246,   60,  115,  272,  122,  265,
       58,   59,  123,   60,  273,  117,  124,  234,  118,   58,
       59,  281,   60,  262,  125,  119,  120,  121,   58,   59,
      282,   60,   58,   59,  122,   60,  204,  155,  123,  126,

       58,   59,  124,   60,  204,   58,   59,  127,   60,  105,
      125,  104,   58,   59,  105,   60,  133,  104,   51,   49,
      135,   58,   59,  134,   60,  126,   57,   58,   59,   53,
       60,   49,   47,  127,   58,   59,  284,   60,   58,   59,
      284,   60,  133,  284,  284,  128,  135,  129,  137,  134,
       58,   59,  136,   60,  284,  130,   58,   59,  284,   60,
      131,  132,  284,   58,   59,  138,   60,  140,  284,  139,
      284,  128,  284,  129,  137,  284,   58,   59,  136,   60,
      284,  130,  141,  284,  284,  284,  131,  132,  284,   58,
       59,  138,   60,  140,  284,  139,   58,   59,  144,   60,

       58,   59,  284,   60,   58,   59,  284,   60,  141,  145,
      284,   58,   59,  147,   60,  142,   58,   59,  284,   60,
      284,  146,  284,  143,  144,   58,   59,  284,   60,  284,
       58,   59,  149,   60,  284,  145,  150,   58,   59,  147,
       60,  142,  148,   58,   59,  284,   60,  146,  284,  143,
      284,   58,   59,  284,   60,  152,  151,  284,  149,  284,
      284,  284,  150,  153,   58,   59,  159,   60,  148,  284,
      284,   58,   59,  284,   60,   58,   59,  284,   60,  284,
      284,  152,  151,   58,   59,  284,   60,   58,   59,  153,
       60,  160,   51,  161,   58,   59,  284,   60,  269,   58,

       59,  270,   60,   58,   59,  284,   60,   58,   59,  284,
       60,  165,  162,  284,  163,   58,   59,  160,   60,  161,
      164,   58,   59,  166,   60,   58,   59,  167,   60,  284,
      170,   58,   59,  168,   60,  169,  284,  165,  162,  284,
      163,   58,   59,  284,   60,  284,  164,   58,   59,  166,
       60,   58,   59,  167,   60,  174,  170,  171,  172,  168,
      173,  169,   58,   59,  284,   60,   58,   59,  284,   60,
      284,  175,   58,   59,  284,   60,   58,   59,  284,   60,
      284,  174,  177,  171,  172,  284,  173,  284,  179,  284,
      176,   58,   59,  284,   60,  178,  284,  175,   58,   59,

      284,   60,  284,   58,   59,  284,   60,  180,  177,  284,
      181,  284,  284,  284,  179,  182,  176,   58,   59,  284,
       60,  178,   58,   59,  284,   60,   58,   59,  284,   60,
      284,   58,   59,  180,   60,  284,  181,  284,  185,  183,
      187,  182,  186,  184,  188,   58,   59,  284,   60,   58,
       59,  284,   60,   58,   59,  284,   60,   58,   59,  284,
       60,  284,  284,  284,  185,  183,  284,  284,  186,  184,
       58,   59,  284,   60,   58,   59,  189,   60,   58,   59,
      284,   60,  190,   58,   59,  284,   60,  284,   58,   59,
      192,   60,  194,  191,  284,  284,  284,   58,   59,  284,

       60,  284,  189,   58,   59,  284,   60,  284,  190,   58,
       59,  284,   60,  195,   58,   59,  192,   60,  193,  191,
      284,   58,   59,  284,   60,  284,   58,   59,  196,   60,
       58,   59,  284,   60,  199,   58,   59,  284,   60,  195,
      284,  197,  284,  284,  193,  198,  284,   58,   59,  284,
       60,  284,   58,   59,  196,   60,   58,   59,  200,   60,
      199,   58,   59,  284,   60,  201,  284,  197,  284,  284,
      284,  198,  202,  207,   58,   59,  284,   60,   58,   59,
      284,   60,   58,   59,  200,   60,   58,   59,  284,   60,
      208,  201,   58,   59,  284,   60,  284,  284,  202,  207,

       58,   59,  284,   60,  284,  209,  284,   58,   59,  210,
       60,   58,   59,  284,   60,  284,  208,   58,   59,  284,
       60,   58,   59,  284,   60,   58,   59,  211,   60,   58,
       59,  209,   60,  213,  284,  210,   58,   59,  284,   60,
       58,   59,  284,   60,  212,   58,   59,  284,   60,   58,
       59,  284,   60,  211,   58,   59,  214,   60,  284,  213,
      284,   58,   59,  215,   60,  284,  216,  284,   58,   59,
      212,   60,   58,   59,  284,   60,   58,   59,  284,   60,
      218,  284,  214,   58,   59,  217,   60,   58,   59,  215,
       60,  284,  216,  219,  284,   58,   59,  220,   60,   58,

       59,  284,   60,  284,   58,   59,  218,   60,  284,   58,
       59,  217,   60,  284,   58,   59,  284,   60,  224,  219,
      284,  284,  284,  220,  225,   58,   59,  284,   60,  223,
       58,   59,  284,   60,   58,   59,  284,   60,   58,   59,
      284,   60,   58,   59,  224,   60,  227,  284,   58,   59,
      225,   60,  284,   58,   59,  223,   60,   58,   59,  284,
       60,   58,   59,  284,   60,  230,   58,   59,  284,   60,
      228,  284,  227,  231,  284,  229,   58,   59,  238,   60,
      284,  284,  284,   58,   59,  284,   60,   58,   59,  284,
       60,  230,   58,   59,  284,   60,  228,   58,   59,  231,

       60,  229,  284,  237,  239,   58,   59,  284,   60,  240,
      284,   58,   59,  241,   60,   58,   59,  284,   60,   58,
       59,  242,   60,   58,   59,  284,   60,  284,  284,  237,
      239,   58,   59,  243,   60,  240,  284,   58,   59,  241,
       60,   58,   59,  244,   60,   58,   59,  242,   60,   58,
       59,  284,   60,   58,   59,  284,   60,  252,  284,  243,
       58,   59,  284,   60,   58,   59,  284,   60,  245,  244,
       58,   59,  284,   60,   58,   59,  258,   60,   58,   59,
      253,   60,  259,  252,   58,   59,  257,   60,   58,   59,
      284,   60,   58,   59,  245,   60,   58,   59,  284,   60,

      260,  284,  258,  284,   58,   59,  253,   60,  259,  284,
       58,   59,  257,   60,   58,   59,  284,   60,   58,   59,
      284,   60,  284,  284,  284,  264,  260,   58,   59,  284,
       60,   58,   59,  284,   60,   58,   59,  267,   60,   58,
       59,  284,   60,   58,   59,  284,   60,   58,   59,  284,
       60,  264,   58,   59,  284,   60,   58,   59,  284,   60,
      284,   58,   59,  267,   60,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  277,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      277,   46,   46,   46,   46,   46,   46,   48,   48,   48,
       48,   48,   48,   50,   50,   50,   50,   50,   50,   61,
       61,   61,   61,   60,   60,   60,   60,  157,  284,  157,
      157,  156,  284,  156,  156,  236,  284,  284,  236,  236,
      248,  284,  284,  248,  248,  251,  284,  284,  251,  251,
      256,  284,  284,  256,  256,  235,  284,  284,  235,  235,
      247,  284,  284,  247,  247,  250,  284,  284,  250,  250,
      255,  284,  284,  255,  255,  274,  284,  284,  274,  274,
      273,  284,  284,  273,  273,    5,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_chk[1458] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   20,  302,   20,   22,   22,   52,   25,   25,
       11,   25,   26,   26,  106,   26,   52,  106,   28,   28,
      296,   28,   30,   30,   26,   30,   28,   60,   60,   25,

       28,   53,  295,   53,   25,   29,   29,   25,   29,   31,
       31,   30,   31,   28,   26,   35,   35,   30,   35,  294,
       26,  108,   28,  103,  157,   25,   28,  157,   34,   34,
       25,   34,  103,   25,   31,  293,   29,   30,  289,   28,
       26,   27,   27,   30,   27,   32,   32,  108,   32,   27,
       34,   33,   33,   32,   33,  158,   27,   32,   36,   36,
       31,   36,   29,   27,   61,   61,   27,   61,  283,  205,
       37,   37,   33,   37,   36,   27,   34,   33,   37,   32,
       36,  158,   27,   32,  282,  203,   37,   38,   38,   27,
       38,  203,   27,   39,   39,  205,   39,  280,   33,  270,

       36,  278,  154,   33,   37,  270,   36,   40,   40,   38,
       40,  154,   37,   63,   39,   38,   42,   42,   39,   42,
      206,  276,   63,   63,   42,   63,  275,  206,   42,   40,
       43,   43,   63,   43,  232,   38,   62,   62,  273,   62,
       39,   38,  221,  232,   39,   45,   45,   62,   45,  221,
       42,   43,  269,   43,   42,   40,   41,   41,   63,   41,
       45,  269,   44,   44,  272,   44,   64,   64,   41,   64,
       44,   41,  271,   62,  222,  268,  266,   43,   44,   43,
       64,  222,   66,   66,   41,   66,   45,  265,   41,   65,
       65,  262,   65,  226,   41,  236,   44,   41,   67,   67,

      226,   67,  236,   65,   44,  255,   64,  254,   68,   68,
       41,   68,   69,   69,   41,   69,   68,   67,   70,   70,
      248,   70,   71,   71,  251,   71,  250,  248,  256,   65,
       70,  251,   69,   72,   72,  256,   72,  263,   73,   73,
       69,   73,   68,   67,  263,   74,   74,  249,   74,   71,
       75,   75,   72,   75,   76,   76,   70,   76,   69,   72,
       73,   74,   77,   77,  247,   77,   69,  274,   74,  246,
       78,   78,   75,   78,  274,   71,   76,  235,   72,   81,
       81,  279,   81,  234,   77,   72,   73,   74,   79,   79,
      279,   79,   89,   89,   74,   89,  204,  156,   75,   78,

       82,   82,   76,   82,  155,   83,   83,   79,   83,  105,
       77,  104,   84,   84,   58,   84,   82,   54,   50,   48,
       84,   85,   85,   83,   85,   78,   24,   86,   86,   17,
       86,   10,    9,   79,   80,   80,    5,   80,   87,   87,
        0,   87,   82,    0,    0,   80,   84,   80,   86,   83,
       88,   88,   85,   88,    0,   80,   90,   90,    0,   90,
       80,   80,    0,   91,   91,   87,   91,   90,    0,   88,
        0,   80,    0,   80,   86,    0,   93,   93,   85,   93,
        0,   80,   91,    0,    0,    0,   80,   80,    0,   94,
       94,   87,   94,   90,    0,   88,   92,   92,   93,   92,

       95,   95,    0,   95,   96,   96,    0,   96,   91,   94,
        0,   97,   97,   96,   97,   92,   98,   98,    0,   98,
        0,   95,    0,   92,   93,   99,   99,    0,   99,    0,
      107,  107,   98,  107,    0,   94,   99,  100,  100,   96,
      100,   92,   97,  101,  101,    0,  101,   95,    0,   92,
        0,  102,  102,    0,  102,  101,  100,    0,   98,    0,
        0,    0,   99,  102,  109,  109,  110,  109,   97,    0,
        0,  110,  110,    0,  110,  111,  111,    0,  111,    0,
        0,  101,  100,  112,  112,    0,  112,  113,  113,  102,
      113,  111,  261,  112,  114,  114,    0,  114,  261,  115,

      115,  261,  115,  116,  116,    0,  116,  120,  120,    0,
      120,  116,  113,    0,  114,  117,  117,  111,  117,  112,
      115,  118,  118,  117,  118,  119,  119,  117,  119,    0,
      120,  121,  121,  118,  121,  119,    0,  116,  113,    0,
      114,  122,  122,    0,  122,    0,  115,  123,  123,  117,
      123,  124,  124,  117,  124,  123,  120,  121,  121,  118,
      122,  119,  125,  125,    0,  125,  126,  126,    0,  126,
        0,  124,  127,  127,    0,  127,  128,  128,    0,  128,
        0,  123,  126,  121,  121,    0,  122,    0,  128,    0,
      125,  129,  129,    0,  129,  127,    0,  124,  130,  130,

        0,  130,    0,  131,  131,    0,  131,  129,  126,    0,
      130,    0,    0,    0,  128,  131,  125,  132,  132,    0,
      132,  127,  133,  133,    0,  133,  134,  134,    0,  134,
        0,  135,  135,  129,  135,    0,  130,    0,  134,  132,
      136,  131,  135,  133,  137,  136,  136,    0,  136,  137,
      137,    0,  137,  138,  138,    0,  138,  139,  139,    0,
      139,    0,    0,    0,  134,  132,    0,    0,  135,  133,
      140,  140,    0,  140,  141,  141,  139,  141,  142,  142,
        0,  142,  140,  143,  143,    0,  143,    0,  144,  144,
      142,  144,  145,  141,    0,    0,    0,  145,  145,    0,

      145,    0,  139,  146,  146,    0,  146,    0,  140,  147,
      147,    0,  147,  146,  148,  148,  142,  148,  144,  141,
        0,  149,  149,    0,  149,    0,  150,  150,  147,  150,
      151,  151,    0,  151,  150,  152,  152,    0,  152,  146,
        0,  148,    0,    0,  144,  149,    0,  153,  153,    0,
      153,    0,  160,  160,  147,  160,  161,  161,  151,  161,
      150,  162,  162,    0,  162,  152,    0,  148,    0,    0,
        0,  149,  153,  160,  163,  163,    0,  163,  164,  164,
        0,  164,  165,  165,  151,  165,  166,  166,    0,  166,
      163,  152,  167,  167,    0,  167,    0,    0,  153,  160,

      168,  168,    0,  168,    0,  164,    0,  169,  169,  165,
      169,  170,  170,    0,  170,    0,  163,  171,  171,    0,
      171,  172,  172,    0,  172,  173,  173,  168,  173,  174,
      174,  164,  174,  173,    0,  165,  175,  175,    0,  175,
      176,  176,    0,  176,  171,  177,  177,    0,  177,  178,
      178,    0,  178,  168,  179,  179,  174,  179,    0,  173,
        0,  180,  180,  176,  180,    0,  177,    0,  181,  181,
      171,  181,  182,  182,    0,  182,  183,  183,    0,  183,
      180,    0,  174,  184,  184,  179,  184,  185,  185,  176,
      185,    0,  177,  181,    0,  186,  186,  182,  186,  189,

      189,    0,  189,    0,  190,  190,  180,  190,    0,  191,
      191,  179,  191,    0,  192,  192,    0,  192,  191,  181,
        0,    0,    0,  182,  192,  193,  193,    0,  193,  190,
      195,  195,    0,  195,  196,  196,    0,  196,  197,  197,
        0,  197,  198,  198,  191,  198,  196,    0,  199,  199,
      192,  199,    0,  200,  200,  190,  200,  201,  201,    0,
      201,  202,  202,    0,  202,  200,  207,  207,    0,  207,
      198,    0,  196,  202,    0,  199,  208,  208,  209,  208,
        0,    0,    0,  209,  209,    0,  209,  212,  212,    0,
      212,  200,  210,  210,    0,  210,  198,  211,  211,  202,

      211,  199,    0,  208,  210,  213,  213,    0,  213,  211,
        0,  214,  214,  212,  214,  215,  215,    0,  215,  216,
      216,  213,  216,  217,  217,    0,  217,    0,    0,  208,
      210,  218,  218,  216,  218,  211,    0,  219,  219,  212,
      219,  220,  220,  218,  220,  223,  223,  213,  223,  224,
      224,    0,  224,  225,  225,    0,  225,  224,    0,  216,
      227,  227,    0,  227,  228,  228,    0,  228,  220,  218,
      229,  229,    0,  229,  230,  230,  228,  230,  231,  231,
      225,  231,  229,  224,  237,  237,  227,  237,  239,  239,
        0,  239,  240,  240,  220,  240,  241,  241,    0,  241,

      230,    0,  228,    0,  242,  242,  225,  242,  229,    0,
      243,  243,  227,  243,  244,  244,    0,  244,  245,  245,
        0,  245,    0,    0,    0,  242,  230,  252,  252,    0,
      252,  253,  253,    0,  253,  257,  257,  252,  257,  258,
      258,    0,  258,  259,  259,    0,  259,  260,  260,    0,
      260,  242,  264,  264,    0,  264,  267,  267,    0,  267,
        0,  277,  277,  252,  277,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  267,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      267,  285,  285,  285,  285,  285,  285,  286,  286,  286,
      286,  286,  286,  287,  287,  287,  287,  287,  287,  288,
      288,  288,  288,  290,  290,  290,  290,  291,    0,  291,
      291,  292,    0,  292,  292,  297,    0,    0,  297,  297,
      298,    0,    0,  298,  298,  299,    0,    0,  299,  299,
      300,    0,    0,  300,  300,  301,    0,    0,  301,  301,
      303,    0,    0,  303,  303,  304,    0,    0,  304,  304,
      305,    0,    0,  305,  305,  306,    0,    0,  306,  306,
      307,    0,    0,  307,  307,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lex_sql.l"

#line 28 "lex_sql.l"
#include<string.h>
#include<stdio.h>

/**
 * flex 代码包含三个部分，使用 %% 分隔
 * 第一个部分的代码是C代码，flex会原样复制到目标文件中
 * 第二个部分是规则部分，使用正则表达式定义一系列规则
 * 第三个部分还是C代码，flex 会复制此段代码
 */

#include "sql/parser/parse_defs.h"
#include "common/log/log.h"
#include "yacc_sql.hpp"

#ifndef register
#define register 
#endif // register

extern int atoi();
extern double atof();

#define RETURN_TOKEN(token) LOG_DEBUG("%s", #token); return token
#line 913 "lex_sql.cpp"
/* Prevent the need for linking with -lfl */
#define YY_NO_INPUT 1
/* 不区分大小写 */

/* 规则匹配的优先级：*/
/* 1. 匹配的规则长的优先 */
/* 2. 写在最前面的优先 */
/* yylval 就可以认为是 yacc 中 %union 定义的结构体(union 结构) */
#line 922 "lex_sql.cpp"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 75 "lex_sql.l"


#line 1208 "lex_sql.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1386 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "lex_sql.l"
// ignore whitespace
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 78 "lex_sql.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  printf("Current string: %s\n", yylval->string);
  RETURN_TOKEN(ID_DOT_ID_MINUS);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  printf("Current string: %s\n", yylval->string);
  RETURN_TOKEN(ID_MINUS);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  RETURN_TOKEN(MIN_MINUS);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  RETURN_TOKEN(MAX_MINUS);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  RETURN_TOKEN(AVG_MINUS);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 107 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  RETURN_TOKEN(SUM_MINUS);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "lex_sql.l"
{
  yylval->string = strdup(yytext);
  RETURN_TOKEN(COUNT_MINUS);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "lex_sql.l"
{
  yylval->string = strdup(yytext + 3);
  printf("Current string: %s\n", yylval->string);
  RETURN_TOKEN(ID);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 123 "lex_sql.l"
yylval->number=atoi(yytext); RETURN_TOKEN(NUMBER);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 124 "lex_sql.l"
yylval->floats=(float)(atof(yytext)); RETURN_TOKEN(FLOAT);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 126 "lex_sql.l"
RETURN_TOKEN(SEMICOLON);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "lex_sql.l"
RETURN_TOKEN(DOT);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 128 "lex_sql.l"
RETURN_TOKEN(EXIT);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 129 "lex_sql.l"
RETURN_TOKEN(IN);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 130 "lex_sql.l"
RETURN_TOKEN(EXISTS);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 131 "lex_sql.l"
RETURN_TOKEN(HELP);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "lex_sql.l"
RETURN_TOKEN(DESC);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "lex_sql.l"
RETURN_TOKEN(CREATE);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 134 "lex_sql.l"
RETURN_TOKEN(DROP);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 135 "lex_sql.l"
RETURN_TOKEN(TABLE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "lex_sql.l"
RETURN_TOKEN(VIEW);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 137 "lex_sql.l"
RETURN_TOKEN(TABLES);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "lex_sql.l"
RETURN_TOKEN(INDEX);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "lex_sql.l"
RETURN_TOKEN(ON);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "lex_sql.l"
RETURN_TOKEN(SHOW);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "lex_sql.l"
RETURN_TOKEN(SYNC);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "lex_sql.l"
RETURN_TOKEN(SELECT);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "lex_sql.l"
RETURN_TOKEN(CALC);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "lex_sql.l"
RETURN_TOKEN(UNIQUE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "lex_sql.l"
RETURN_TOKEN(FROM);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "lex_sql.l"
RETURN_TOKEN(WHERE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "lex_sql.l"
RETURN_TOKEN(AND);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "lex_sql.l"
RETURN_TOKEN(INSERT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "lex_sql.l"
RETURN_TOKEN(INTO);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 150 "lex_sql.l"
RETURN_TOKEN(VALUES);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "lex_sql.l"
RETURN_TOKEN(DELETE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "lex_sql.l"
RETURN_TOKEN(UPDATE);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "lex_sql.l"
RETURN_TOKEN(SET);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 154 "lex_sql.l"
RETURN_TOKEN(TRX_BEGIN);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "lex_sql.l"
RETURN_TOKEN(TRX_COMMIT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 156 "lex_sql.l"
RETURN_TOKEN(TRX_ROLLBACK);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 157 "lex_sql.l"
RETURN_TOKEN(INT_T);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "lex_sql.l"
RETURN_TOKEN(STRING_T);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "lex_sql.l"
RETURN_TOKEN(FLOAT_T);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "lex_sql.l"
RETURN_TOKEN(DATE_T);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "lex_sql.l"
RETURN_TOKEN(LOAD);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "lex_sql.l"
RETURN_TOKEN(TEXT_T);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "lex_sql.l"
RETURN_TOKEN(DATA);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "lex_sql.l"
RETURN_TOKEN(INFILE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "lex_sql.l"
RETURN_TOKEN(EXPLAIN);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 166 "lex_sql.l"
RETURN_TOKEN(LIKE);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "lex_sql.l"
RETURN_TOKEN(NOT);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 168 "lex_sql.l"
RETURN_TOKEN(MIN);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 169 "lex_sql.l"
RETURN_TOKEN(MAX);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 170 "lex_sql.l"
RETURN_TOKEN(AVG);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 171 "lex_sql.l"
RETURN_TOKEN(SUM);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 172 "lex_sql.l"
RETURN_TOKEN(COUNT);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 173 "lex_sql.l"
RETURN_TOKEN(INNER);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 174 "lex_sql.l"
RETURN_TOKEN(JOIN);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 175 "lex_sql.l"
RETURN_TOKEN(NULL_IS);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 176 "lex_sql.l"
RETURN_TOKEN(OB_NULL);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 177 "lex_sql.l"
RETURN_TOKEN(ORDER);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 178 "lex_sql.l"
RETURN_TOKEN(BY);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 179 "lex_sql.l"
RETURN_TOKEN(ASC);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 180 "lex_sql.l"
RETURN_TOKEN(AS);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 181 "lex_sql.l"
RETURN_TOKEN(GROUP);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 182 "lex_sql.l"
RETURN_TOKEN(OR);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 183 "lex_sql.l"
RETURN_TOKEN(HAVING);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 184 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(ID);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 185 "lex_sql.l"
RETURN_TOKEN(LBRACE);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 186 "lex_sql.l"
RETURN_TOKEN(RBRACE);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 188 "lex_sql.l"
RETURN_TOKEN(COMMA);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 189 "lex_sql.l"
RETURN_TOKEN(EQ);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 190 "lex_sql.l"
RETURN_TOKEN(LE);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 191 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 192 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 193 "lex_sql.l"
RETURN_TOKEN(LT);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 194 "lex_sql.l"
RETURN_TOKEN(GE);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 195 "lex_sql.l"
RETURN_TOKEN(GT);
	YY_BREAK
case 82:
#line 198 "lex_sql.l"
case 83:
#line 199 "lex_sql.l"
case 84:
#line 200 "lex_sql.l"
case 85:
YY_RULE_SETUP
#line 200 "lex_sql.l"
{ return yytext[0]; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 201 "lex_sql.l"
{ yylval->string = strdup(yytext); RETURN_TOKEN(DATE_STR); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 202 "lex_sql.l"
{ yylval->string = strdup(yytext); RETURN_TOKEN(SSS); }
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 203 "lex_sql.l"
{ yylval->string = strdup(yytext); RETURN_TOKEN(SSS); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 205 "lex_sql.l"
LOG_DEBUG("Unknown character [%c]", yytext[0]); return yytext[0];
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 206 "lex_sql.l"
ECHO;
	YY_BREAK
#line 1736 "lex_sql.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 284);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 206 "lex_sql.l"


void scan_string(const char *str, yyscan_t scanner) {
  yy_switch_to_buffer(yy_scan_string(str, scanner), scanner);
}

